apiVersion: v1
kind: ConfigMap
data:
  index.html: <!DOCTYPE html><html lang=en><meta charset=utf-8><title>AKS Sample Application</title><body><style>body{background-color:#bfd6ff}</style><h2>Hello
    from Blue Web Service</h2>
metadata:
  name: nginx-blue
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-web
  labels:
    app: ingress-demo
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-demo
      color: blue
  template:
    metadata:
      labels:
        app: ingress-demo
        color: blue
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-blue
        resources: {}
        volumeMounts:
        - name: index
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
      - name: index
        configMap:
          name: nginx-blue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-demo
    color: blue
  name: blue-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ingress-demo
    color: blue
  sessionAffinity: None
  type: ClusterIP

